### PR TITLE
Serverside coffeescript

### PR DESCRIPTION
**Pull request by harryoh**
I love angular-fullstack and coffeescript.

So I implemented angular-fullstack can generate coffeescripts in the server side.

I hope some nice guy can improve this.

### CODE REVIEW

**Comment by CarlRosell** [comment]
:+1:

**Comment by wmertens** [comment]
:+1: Epic.

**Comment by harryoh** [comment]
I wrote serverside coffee for generator-angular-fullstack but did't push them.
Please let me know if anyone need.
I'll show them.

**Comment by marcosanson** [comment]
@harryoh where I can find your changes in order to create server side files in coffeescript?

**Comment by harryoh** [comment]
@marcosanson Hi guy, go to https://github.com/DaftMonk/generator-angular-fullstack/compare/master...harryoh:serverside-coffee

But I think you should fix minor bugs.

**Comment by harryoh** [comment]
I create new generator for server-side coffee script.
visit to https://github.com/harryoh/generator-coffee-fullstack

**Pull request closed without merging**
