### PR TITLE
Authorization for UI-Router

### PR DESCRIPTION
**Pull request by trainerbill**
option to add authoirze: 'admin' to the state to only allow admin users access to the state.

### CODE REVIEW

**Comment by Awk34** [comment]
Does this have any upside when compared to what's already being done in `app.js`?

**Comment by trainerbill** [comment]
Not sure what you mean by whats already being don in app.js.  This allows you to add an authorize: parameter on the ui-router configuration which requires the user to have a specific role.

**Comment by Awk34** [comment]
@trainerbill sorry I misunderstood what the PR was. Would you please also update the coffescript files?

**Comment by Awk34** [comment]
Closed due to inactivity.

**Pull request closed without merging**
