### PR TITLE
chore(gen): use svg badges in `README.md`

### PR DESCRIPTION
**Pull request by kingcody**

### CODE REVIEW

**Comment by kingcody** [comment]
Should I add the dev-dependencies badge for the generator to this PR?

**Comment by kingcody** [comment]
Added the dev-dependencies badge and moved the gitter badge to the next line. You can view the changes [here](https://github.com/DaftMonk/generator-angular-fullstack/blob/chore/svg-badges/readme.md).

**Comment by Awk34** [comment]
Might as well put all the badges on new lines; makes everything more readable.

**Comment by kingcody** [comment]
Hmm, well it seems for markdown there has to be a blank line between images for them to not be inline, which adds a lot of whitespace: https://github.com/DaftMonk/generator-angular-fullstack/blob/f435c4fb5526a6fb2eeba379b511871f189e2f76/readme.md

**Comment by Awk34** [comment]
Yeah I just mean't like this:

```
[![Build Status](https://travis-ci.org/DaftMonk/generator-angular-fullstack.svg?branch=master)](http://travis-ci.org/DaftMonk/generator-angular-fullstack)
[![npm version](https://badge.fury.io/js/generator-angular-fullstack.svg)](http://badge.fury.io/js/generator-angular-fullstack)
[![Dependency Status](https://david-dm.org/daftmonk/generator-angular-fullstack.svg)](https://david-dm.org/daftmonk/generator-angular-fullstack) [![Dev-Dependency Status](https://david-dm.org/daftmonk/generator-angular-fullstack/dev-status.svg)](https://david-dm.org/daftmonk/generator-angular-fullstack#info=devDependencies)
+[![Gitter chat](https://badges.gitter.im/DaftMonk/generator-angular-fullstack.svg)](https://gitter.im/DaftMonk/generator-angular-fullstack)
```

**Comment by kingcody** [comment]
Yeah, that makes sense.

**Comment by kingcody** [comment]
https://github.com/DaftMonk/generator-angular-fullstack/blob/chore/svg-badges/readme.md

**Pull request merged**
