### PR TITLE
Update passport auth api

### PR DESCRIPTION
**Pull request by adamk33n3r**
There have been some API changes.
As of July 8th Facebook introduced v2.4 of their API. The default request only responds with `id` and `name` now. If you create a Facebook app after July 8th you are forced to use v2.4 so this breaks the app (even though passport is currently defaulted to use v2.2, Facebook forces you).

The User model didn't actually have a username attribute which the oauth services were using.

### CODE REVIEW

**Comment by kingcody** [comment]
@adamk33n3r, thank you for your time and efforts. Have you by chance read the [contributing guide](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)? It outlines this project's commit style and which branch is for development, along with some other useful info.

**Comment by adamk33n3r** [comment]
@kingcody My apologies. I did not. I will. Would these things warrant tests?

**Comment by Awk34** [comment]
Most likely. If you could, only include the code to fix OAuth stuff in the new PR. Adding a `username` field to the user model is something we might do in the future, but it would warrant some more work.

Also, you might want to make a new PR off of the `canary` branch instead of `master`.

**Comment by kingcody** [comment]
@adamk33n3r seeing as we don't have FB or Google api creds for testing I'd say they could be omitted.

**Comment by adamk33n3r** [comment]
@Awk34 Ok I can do those things. I just added the username field because in the passport files you have it setting the username field so I thought that was what was intended.

**Pull request closed without merging**
