### PR TITLE
feat(app): implement navbar as directive

### LINKED ISSUE #457: Navbar as Directive
Just wondering if anyone else has considered this?

I normally implement it as a directive and it seems to be fairly beneficial. Allows for easier includes and more control over its setup.

### PR DESCRIPTION
**Pull request by kingcody**
closes #457

### CODE REVIEW

**Comment by Awk34** [comment]
I like this, but can you change them to not be self-closing tags? The HTML spec is very particular about void tags..

**Comment by kingcody** [comment]
Absolutely

**Comment by Awk34** [comment]
Thanks :D

**Comment by Awk34** [comment]
BTW we should probably also do this for the footer... *wink* if you're up for it

**Comment by kingcody** [comment]
Its on my list (:

**Comment by Awk34** [comment]
Oh, just searched, I already made a task for it: #1032. Want me to assign you?

**Comment by kingcody** [comment]
Do it

**Comment by Awk34** [comment]
Oops, looks like I can only assign collaborators. I'll try to get you as one :+1:

**Pull request merged**
