### PR TITLE
chore(package.json): update jwt versions

### PR DESCRIPTION
**Pull request by yinzer**
update jwt packages due to security vulnerabilities

### CODE REVIEW

**Comment by Awk34** [comment]
:+1:

**Comment by arnauldvm** [comment]
:+1:

**Comment by arnauldvm** [comment]
socketio-jwt should be updated to 4.0.0
See https://github.com/auth0/socketio-jwt/issues/40

**Comment by MichaelJCole** [comment]
This is a big deal and should be done immediately.

For more info: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Pull request merged**
