### PR TITLE
feat(gen): always use Babel

### PR DESCRIPTION
**Pull request by Awk34**
leave in supporting code for use with eventually supporting typescript

### CODE REVIEW

**Comment by Awk34** [comment]
damn you sauce labs..

**Comment by kingcody** [comment]
We still need to set `filters.js` since ng-component uses it (else, it won't generate any scripts).

**Comment by kingcody** [comment]
If we're looking to support typescript, maybe we should just leave the `(js)` filter in file names for now?

**Comment by Awk34** [comment]
I don't think we'll need it

**Comment by kingcody** [comment]
> I don't think we'll need it

In reply to `(js)` or `filters.js`?

**Comment by Awk34** [comment]
`(js)`

**Comment by kingcody** [comment]
@Awk34 I rebased this.

**Comment by kingcody** [comment]
I'm sure sauce labs will fail initially with too many concurrent tests...

**Pull request merged**
