### PR TITLE
When using endpointDirectory includes endpoint name

### PR DESCRIPTION
**Pull request by adamk33n3r**
This adds the endpoint name after the endpointDirectory config option if supplied.

### CODE REVIEW

**Comment by ZaLiTHkA** [comment]
Just to check.. The other day I tried to generate an endpoint at `company/detail` and ended up with the following:

* a path of `[proj]/server/api/company/detail/company/detail.controller.js`
* variables in the module files were all `company/detail` instead of `detail`

Is this change intended to correct this behaviour, or is this for something else?

**Comment by adamk33n3r** [comment]
This is for something different. I've never encountered your issue though. What command did you run exactly?

**Comment by ZaLiTHkA** [comment]
Ah, ok.. No worries then. I ran `yo angular-fullstack:endoint company/detail`, hoping to simply get a `detail` endpoint inside a `company` dir.

Anyways, I don't really want to derail this PR, so I'll try reproduce it in a clean project and post a new report about it. This was the closest I found when searching this repo for more info, so I thought I'd ask just in case. :)

**Comment by adamk33n3r** [comment]
Ah. So actually you need to run the generator with just the endpoint name as a parameter like 'detail'. Then when the command is run it asks you for dir and that's when you put 'api/company' or something like that. 

No worries about derailing. Always happy to help people.

**Comment by ZaLiTHkA** [comment]
Thanks for the suggestion, that is actually what I ended up with anyway; but the endpoint generator only prompts for the endpoint URL, not the folder path... It works this way, but I'm (a software tester by trade and) too pedantic to settle for simply "it works".

Anyways, I posted a more detailed query at #934 to see if I get some more clarification on this.

**Comment by kingcody** [comment]
@adamk33n3r do you think this change could be accomplished with:
```javascript
var dest = (this.config.get('endpointDirectory') || 'server/api/') + this.name;
```

**Comment by kingcody** [comment]
I'm going to close this PR as this functionality is covered in #1122 (along with others). Please feel free to discuss the implementation there.

**Pull request closed without merging**
