### PR TITLE
Endpoint improvements

### PR DESCRIPTION
**Pull request by kingcody**

### CODE REVIEW

**Comment by kingcody** [comment]
closes #647, closes #934

**Comment by Awk34** [comment]
:+1:

**Comment by kingcody** [comment]
@Awk34 we may want to merge #1135 before this, I'll rebase and test against `yeoman-generator@~0.18.0`. There are a few things I can clean up since they were just backports of `>=0.18.0` functions.

**Comment by Awk34** [comment]
@kingcody merged #1135 . Go ahead with this one if its ready.

**Comment by kingcody** [comment]
Turns out the backports aren't fully implemented until `~0.20.0`. Gonna go ahead a merge this.

**Pull request merged**
