### PR TITLE
Merge canary into master

### PR DESCRIPTION
**Pull request by Awk34**

### CODE REVIEW

**Comment by Awk34** [comment]
Did my best to merge conflicts. There were a crapload of them.

**Comment by kingcody** [comment]
There are some issue that I think should be addressed before merging canary into master.

- [ ] Endpoint needs sequelize support
- [ ] Server-side babel support
- [ ] #1012 & #1013 (IMHO)
- [ ] General testing with added features and updated libs (?)

**Comment by Awk34** [comment]
Looks like the only two things failing now are Babel and E2E

**Comment by Awk34** [comment]
@kingcody are you using server-side Babel? I've just been using Node.js 12 with `--harmony`.

**Comment by kingcody** [comment]
@Awk34, I've been using ES6 server-side with the babel require hook. I'll submit a PR later tonight.

**Comment by Awk34** [comment]
@kingcody , want to make a list of tests we should add for this?

**Comment by Awk34** [comment]
I've made [another branch](https://github.com/DaftMonk/generator-angular-fullstack/tree/legacy-2.x.x) off of master that we can use to update the 2.x.x code. I think we should go ahead with this PR. Sound good @kingcody ?

**Comment by kingcody** [comment]
> I've made another branch off of master that we can use to update the 2.x.x code.

Awesome!

Do we want to complete [milestone/3.0.0](https://github.com/DaftMonk/generator-angular-fullstack/milestones/3.0.0) first?

**Comment by Awk34** [comment]
I'd say we merge it now. Bug fixes for 2.x.x will go on the branch I mentioned earlier, bug fixes for 3.x.x will go on master, and new features for 3.x.x can go on canary.

**Comment by kingcody** [comment]
#1193 and #1164, did you want to merge those before or wait for a point release?

**Comment by Awk34** [comment]
Yeah, we'll still going to wait to do the release of `3.0.0`. There's quite a few other things I'd like to get in before then. I was just going to merge the PR for now.

**Comment by kingcody** [comment]
Ah, that makes sense.

**Pull request merged**
