### PR TITLE
Fix: update socketio & doc info

### PR DESCRIPTION
**Pull request by kingcody**
Changes:
* Update socket.io and related deps
* Update socketio-jwt doc comment
* Update `socket.address` reference

### CODE REVIEW

**Comment by kingcody** [comment]
@Awk34 looks like this PR disappeared somehow.

**Comment by Awk34** [comment]
I am confuse

**Comment by kingcody** [comment]
The two commits that are listed here are not included in the `canary` commit history.

**Comment by Awk34** [comment]
haha yeah that's why I'm confused

**Comment by kingcody** [comment]
I can just re submit these two PRs.

**Pull request merged**
