### PR TITLE
Add support for Gulp

### PR DESCRIPTION
**Pull request by Pentiado**
I've been working recently on awesome project and I was tried of waiting until my code gets compiled and browser refreshed. Right now I'm thinking if I'm not uber procrastinator because I've spend about three days working on open source project instead of finishing my own ; )

It is not perfect, on my old macbook pro I have to wait like twice longer than when editing in Chrome console but I understand that compiling coffee or stylus and page refresh might take a while, about blink of an eye.

What it do?
- most of the stuff that grunt but FASTER and in awesome way ; )
- stylus with nib
- first question asks if you want to choice experimental Gulp instead of Grunt so there will be no harm for Grunt lovers

What it can't do?
- compass
- when using Jade automatically inject scripts after build

### CODE REVIEW

**Comment by Yago** [comment]
This PR seems deprecated, but what is the state of Gulp integration @DaftMonk ?

**Comment by stewones** [comment]
+1

**Comment by Kesarion** [comment]
+1 This is a great idea! Could someone working on the main project make some prerequisites/a plan to get this moving?

**Comment by fnami0316** [comment]
+1

**Comment by nonotest** [comment]
+1

**Comment by ericmdantas** [comment]
If any of you are interested, I'm working on a similar generator, but it'll use gulp as default:

https://github.com/ericmdantas/generator-ng-fullstack

It also has a few differences from this generator.. feedbacks are welcome =]

**Comment by Apercu** [comment]
@ericmdantas I don't think promoting your own generator on this issue is relevant.

**Comment by dancancro** [comment]
@ericmdantas I am begging you on my knees not to make yet another mediocre generator.  [Here's why](https://docs.google.com/spreadsheets/d/1r8rJy2Q5p5QORYKcye93UECwOlSgFL24c5fyF7dqhaM/edit#gid=1445311198).  But I would be happy for you to join the discussion about how to work together on a great one.  Let me know and I'll make you an editor of the trade-offs spreadsheet and include you in the hangout announcements.

**Comment by ericmdantas** [comment]
@Apercu, it's not like I'm getting money or anything, I'm just trying to move things forward.. since this pull request is from April and doesn't look like it's going anywhere - and people are interested in the gulp integration.

@dancancro, To be honest with you, I created this one for my own purposes, so I'd not have to go through all the same initial repetitive stuff. But I'm definetely willing to work on something bigger and more organized - so far I'm the only one pushing stuff there - so, yeah.. please, let me know if you have something.

**Comment by ericmdantas** [comment]
@dancancro, nice link by the way.

**Comment by kosz** [comment]
@dancancro I don't think having multiple choices is a bad thing. Just look at how the two most popular yeoman generators have fallen behind in some areas.

I've read the first 3 syllogisms in that spread sheet, and I feel their angles could be contested. For example, of course having multiple generators would drive innovations, because different ones would uncover different best practices, while due to the nature of open source, these best practices can be shared amongst the different projects, and even encourage merging. And yes the diversity is required, if some people want to use gulp, some people want to use grunt, some people want full stack, some want single app ... it's good to have the options. 

I see where you are coming from, with the exception, that I don't think of competition in open source. The way I see it, that's just taking different independent directions, in order to mature our field faster and with less bias.

**Comment by Kesarion** [comment]
@ericmdantas I actually appreciate it. This project is standing still for some time now, might as well move on. If it ever comes back to life it can definitely make use of a working version of a project inspired from it. This feature, which I would consider high priority was ready long ago and it's been ignored for so long. Your project is perfect timing if anything.

**Comment by Apercu** [comment]
@ericmdantas It's not really about whether you are making money, it's about not using a well known repository for self-promotion. This issue is about *angular-fullstack* gulp integration and should stay as is. I'm sure there is a lot of yeoman generators using gulp in this world :)

**Comment by kosz** [comment]
Apercu, this is a 1 year old, stale pull request. Maybe nobody will see ;)

**Comment by ericmdantas** [comment]
@Kesarion, thanks, man. Glad you found it useful.
About generator-angular-fullstack as a whole, it's a pretty good generator, but looks like it's stuck, we've got almost 50 PRs and they're not going anywhere, which is sad, because people are willing to help, but nothing is happening.

@kosz, I agree with pretty much everything you said about the diversity - it's very good, we learn from each other and all. 

Would I prefer to have one 'perfect' generator for my needs? Of course. 

Would a huge generator full of questions get what I need? I don't know. 

Would be better if we had specialized generators that do certain things very well? Yep. Do they integrate well? I don't know. That'll depend on which generator is organizing them and suchs.
 

@Apercu, sorry if you felt it that way, it was not my intention. But since people are still interested in it even after 1 year of pull request, maybe they didn't find what they were looking for - hence, my post. I could've linked to other generators if I knew any other by head.

**Comment by kosz** [comment]
@ericmdantas I think the answer is not ONE huge generator. I think the answer is MANY small generators working together ;)

**Comment by ericmdantas** [comment]
@kosz, I mean, one 'huge' to rule the small ones.

**Comment by dancancro** [comment]
[I made a survey](https://docs.google.com/forms/d/1xeW8WvlzjJwojAP5r_b3Fxqp5zTGnqrbCgHdxqjFuVA/viewanalytics)

70% of the survey respondents (151 people) want there to only be one generator
15% of the survey respondents (33 people) want there to continue being multiple generators

**Comment by josephfinlayson** [comment]
This is silly. The respondents who all want one generator want one that is
perfect for their needs. Given that is impossible, there will continue
being multiple generators that cater to different tastes.

Joseph Finlayson

+44 796 796 5870
+49 162 395 0220

**Comment by kosz** [comment]
@dancancro, personally, coming from Rails, where things are exactly as you are describing you'd want them, I find the multiple choices that node.js allows me to be very beneficial. 

I feel that going towards that monolithic way of doing things would be a step back rather than forward. But to each his own. 

On another note ... you are saying : "don't create new ones, improve the existing ones". 
And you are making this statement, in the comments of a one year old stale PR which was meant to integrate the up and coming build system in node. Kind of ironic don't you think ? 

So if we should improve, rather than recreate ... What do you want us to do ? Go and have arguments with the maintainers of popular generators about how angular anti patterns should not be promoted by these generators, things like $http calls shouldn't be called in controllers, and things shouldn't be attached directly to the scope ? Then create a pull request that fixes these things, only to have it go stale after one year ? 

I don't know ... I REALLY understand the essence of where you are coming from, but don't confuse parallel innovation efforts with marketing wars. We are not simply slapping brand names on the same technology, we innovate openly, and help our field mature.

**Comment by Pentiado** [comment]
I've spent couple of days on angular generator and made PR both to generator-angular-fullstack and generator-angular. I had time for that because I was using my last days of happy unemployment. With job comes deadlines and later I lost interest in trying to get accepted pull requests. If I would just create another Two generators instead of trying to contribute community would get almost a year ago first angular generators on Gulp and you wouldn't keep adding "+1" here.

**Comment by kosz** [comment]
+1 :D

**Comment by dancancro** [comment]
@kosz  Those are good points.

> Kind of ironic don't you think ?

I sure do.  But that doesn't close the case against the pull request system.  This one hasn't been granted, but lots of them are.  I hate waiting too, so I feel ya.  The system needs some work.

I think one fixable part is finding out what's important to people.  Putting "+1"s in github threads seems a little ridiculous to me.  I made [this](http://dancancro.uservoice.com/forums/287891-general) alternative in UserVoice out of the [benefits](https://docs.google.com/spreadsheets/d/1r8rJy2Q5p5QORYKcye93UECwOlSgFL24c5fyF7dqhaM/edit#gid=1534967054) I've collected about frameworks (Angular, React, etc).  The same could be done for starter (generator) things.  We should have one such set of votable benefits for the whole app development world, not one for each generator project.  And it should be part of github.

And another thing.  That significant work is done in a pull request before it has been approved is weird and backwards in my opinion.  I don't understand why that happens.  It certainly doesn't work that way in a job.

**Comment by dancancro** [comment]
Sure enough. I'm not the first one to think of adding voting to features in github projects.  [Here](https://github.com/isaacs/github/issues/9)'s the issue. [Zenhub](https://www.zenhub.io/) and [UserVoice](www.uservoice.com) were mentioned as solutions.  From reading the issue, I picked up a universal support for it and a universal dislike of +1's.  Somebody said they used to have feature voting in the past on github but it was removed and he didn't say why.

**Pull request closed without merging**
