### PR TITLE
refactor($http): change legacy promise to standard

### LINKED ISSUE #1200: $http legacy promise has been deprecated
[$http Deprecation Notice](https://docs.angularjs.org/api/ng/service/$http#deprecation-notice) tell us `.success` and `.error` method which we have been using have become legacies. [This commit](https://github.com/angular/angular.js/commit/a8f7e9cfde82ed7eaba3a868d8acafdf57f2d76f) is related with this issue. Therefore, I think we have to follow that.

If you take a look [$http General Usage](https://docs.angularjs.org/api/ng/service/$http#general-usage), then get to know response object has changed a little. While `.success` and `.error` callback was returning just response body by default, `.then` is returning object with some useful properties. A callback response that we have got from `.success` and `.error` is **`data` property** that a callback response have in `.then`.

```javascript
// in success
$http.get('/api/things').success(function(awesomeThings) {
  $scope.awesomeThings = awesomeThings;
});

// in then
$http.get('/api/things').then(function(res) {
  $scope.awesomeThings = res.data;
});
```

### PR DESCRIPTION
**Pull request by ligeek**
`success` and `error` promise have been deprecated.

resolves #1200

### CODE REVIEW

**Comment by Awk34** [comment]
This brings up the fact that the JS `admin.controller` file uses `User.query`, while the CoffeeScript one uses `$http`. I'm going to fix the CoffeeScript one.

**Comment by Awk34** [comment]
Requires #1211

**Comment by ligeek** [comment]
Oh, I didn't catch that, thank you. I just remove that coffee file. @Awk34

**Comment by Awk34** [comment]
Awesome, thanks :D

**Pull request merged**
