### PR TITLE
feat(server:auth): add role to signToken

### LINKED ISSUE #382: Wrong number of parameters in signToken method
The method `signToken` from `auth.service.js` is always called with two parameters:
```
var token = signToken(req.user._id, req.user.role);
```
(in `/app/templates/server/auth(auth)/local/index.js` line 15 or in `/app/templates/server/auth(auth)/auth.service.js` line 68)

But the function just accepts one parameter:
```
/**
 * Returns a jwt token signed by the app secret
 */
function signToken(id) {
  return jwt.sign({ _id: id }, config.secrets.session, { expiresInMinutes: 60*5 });
}
``` 

Where are the informations user.id and user.role extrated out of the token and then used?

### PR DESCRIPTION
**Pull request by Awk34**
add role as second parameter, and attach to jwt

closes #382

### CODE REVIEW

**Comment by kingcody** [comment]
No real issues with this, just curious why we don't roll the whole `user.profile`. Any thoughts?

**Comment by Awk34** [comment]
I think the jwt should stick to the more unchanging auth data. Role could
change more easily, but ID won't change and can be quickly used to get all
other data. Also, it keeps the size of the jwt small (since it's used in
every request).

**Comment by kingcody** [comment]
In that case why include the `role` and not just correct the function usage signature?

**Comment by Awk34** [comment]
We're not using it here yet, but I've seen other implementations with role. I think it's to aid in the speed of requests and auth checking

**Pull request merged**
